_target_: src.encoders.ESM2EncoderModel
_partial_: true

config:
  encoder_type: "ESM2-650M"
  encoder_model_name: "facebook/esm2_t33_650M_UR50D"
  statistics_path: "${project.statistics_folder}/encodings-ESM2-650M.pth"

  embedding_dim: 1280