_target_: src.encoders.ESM2EncoderModel
_partial_: true

config:
  encoder_type: "ESM2-8M"
  encoder_model_name: "facebook/esm2_t6_8M_UR50D"
  statistics_path: "${project.statistics_folder}/encodings-ESM2-8M.pth"

  embedding_dim: 320